project:
  type: book

book:
  title: "Curso: Bioestadística 2022"
  subtitle: "Master of Data Science"
  affiliation-title: "Universidad Adolfo Ibáñez - Chile"
  author: "Denis Berroeta González (denis.berroeta@uai.cl)"
  date: "2022-08-12"
  chapters:
    - index.qmd
    - fundamentos.qmd
    - d_prob.qmd
    - t_limite_central.qmd
    - references.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
    html-math-method: katex
    css: style.css

editor: visual
always_allow_html: true
