project:
  type: book

book:
  title: "Curso: Bioestadística 2022"
  subtitle: "Master of Data Science"
  institution: "Universidad Adolfo Ibáñez - Chile"
  author: "Denis Berroeta González (denis.berroeta@uai.cl)"
  date: "2022-08-12"
  chapters:
    - index.qmd
    - fundamentos.qmd
    - references.qmd
  always_allow_html: true

bibliography: references.bib

format:
  html:
    theme: cosmo
    html-math-method: katex
    css: style.css
  pdf:
    documentclass: scrreprt

editor: visual
