---
always_allow_html: yes
---

# Prefacio {#prefacio}

Este libro que contiene los apuntes personales del curso de Bioestadística. [Master of Science](https://ingenieria.uai.cl/master-of-science/master-of-science-in-data-science/), de la Universidad Adolfo Ibañez. Chile 2022.

Porfesor Titular: Prof. Javier Lopatin \| [javier.lopatin\@uai.cl](javier.lopatin@uai.cl)

Principalmente para los procesos análisis de datos y visualización de resultados se usará [R Project](https://www.r-project.org)

## Syllabus

1.  **Introducción al lenguaje de programación R**: Instalación del programa R y RStudio. Lectura de archivos externos. Gráficos y estadística descriptiva. Tipos básicos de herramientas estadísticas.

2.  **Regresión lineal y no lineal**: Correlación, estimación y predicción. Intervalos de confianza. Diagnósticos y Análisis de residuos. Calibración

3.  **Análisis multivariante:** Métodos de reducción de dimensionalidad en los datos. PCA. Análisis de Clusters.

4.  **Análisis de varianza de un factor (one-way ANOVA)**: Fundamentos, métricas y ejemplos de uso.

5.  **Análisis de varianza de dos o más factores (two-way ANOVA)**: Diferencia con ANOVA de un factor. Ejemplos de uso.

6.  **Análisis de covarianza (ANCOVA)**: Fundamentos, métricas y ejemplos de uso.

7.  **Diseños de muestreo**: Muestreo aleatorio simple, estratificado, y sistemático. Muestreo de dos etapas. Determinación del tamaño de la muestra.

8.  **Estadística no paramétrica:** Introducción a la estadística no paramétrica. Cuando utilizarla. Principio de parsimonia.

9.  **Series de tiempo**: Ajuste estacional, media móvil, suavizado exponencial, extrapolación, predicción lineal, Estimación de tendencias, estacionalidad y modelado ARIMA.
